version: 2
updates:
- package-ecosystem: "github-actions"
  open-pull-requests-limit: 99
  directory: "/"
  rebase-strategy: "disabled"
  schedule:
    interval: weekly
    day: "saturday"
    timezone: "Europe/Berlin"
    time: "03:00"
- package-ecosystem: npm
  open-pull-requests-limit: 99
  directory: "/"
  rebase-strategy: "disabled"
  schedule:
    interval: weekly
    day: "saturday"
    timezone: "Europe/Berlin"
    time: "03:00"
  groups:
    eslint:
      applies-to: version-updates
      patterns:
        - "@eslint-community/eslint-plugin-eslint-comments"
        - "@intlify/eslint-plugin-vue-i18n"
        - "@typescript-eslint/*"
        - "eslint-*"
      exclude-patterns:
        - "eslint"
        - "eslint-plugin-vitest"
    pinia:
      applies-to: version-updates
      patterns:
        - "*pinia*"
    react:
      applies-to: version-updates
      patterns:
        - "react*"
    remark:
      applies-to: version-updates
      patterns:
        - "remark*"
    sass:
      applies-to: version-updates
      patterns:
        - "sass*"
    storybook:
      applies-to: version-updates
      patterns:
        - "*storybook*"
    stylelint:
      applies-to: version-updates
      patterns:
        - "*stylelint*"
    typescript:
      applies-to: version-updates
      patterns:
        - "ts*"
        - "*types*"
    vite:
      applies-to: version-updates
      patterns:
        - "*vite*"
    vue:
      applies-to: version-updates
      patterns:
        - "*vue?(/)*"
      exclude-patterns:
        - "vuetify"
        - "*vuepress*"
        - "vue-tsc"
    vuepress:
      applies-to: version-updates
      patterns:
        - "*vuepress*"
- package-ecosystem: docker
  open-pull-requests-limit: 99
  directory: "/"
  rebase-strategy: "disabled"
  schedule:
    interval: weekly
    day: "saturday"
    timezone: "Europe/Berlin"
    time: "03:00"
